# Generated by Django 4.2.6 on 2023-10-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoExames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=1)),
                ('preco', models.FloatField()),
                ('disponicel', models.BooleanField(default=True)),
            ],
        ),
    ]
