# Generated by Django 4.2.6 on 2023-10-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0002_tipoexames_horario_final_tipoexames_horario_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoexames',
            name='tipo',
            field=models.CharField(choices=[('I', 'Imagem'), ('S', 'Sangue')], max_length=1),
        ),
    ]
