# Generated by Django 4.2.6 on 2023-10-05 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0005_pedidosexames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoexames',
            old_name='disponicel',
            new_name='disponivel',
        ),
    ]
